inherit_from: .rubocop_todo.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - node_modules/**/*
    - db/*
    - vendor/ruby/**/*
    - vendor/bundle/**/*
    - config/**/*
    - node_modules/**/*
    - bin
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
Style/FileName:
  Exclude:
    - Gemfile
    - Capfile
Style/Documentation:
  Exclude:
    - app/**/*
    - db/**/*
Style/FrozenStringLiteralComment:
  Exclude:
    - db/**/*

