default: &default
  mailer:
    url:
      host: <%= ENV['MAILER_HOST'] %>
  tamashii:
    mode: token
    token: <%= ENV['TAMASHII_TOKEN'] %>
  pansci:
    api_uri: http://stage.events.panmedia.asia

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
